webhook: allow patching updated workloads
Previously, Wavy was only able to patch newly created workloads. Now,
Wavy is able to patch workloads that have been updated, with one
exception: Pods cannot be patched because Kubernetes does not permit
updating the fields that Wavy needs to change on a running Pod.

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>